# Derived from https://github.com/cal-icor/base-user-image/blob/main/environment.yml
name: sp26

channels:
  - conda-forge
  
dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds=4.1
  - git==2.5.0
  - ipython==9.9.0
  - jupyter-resource-usage=1.2
  - jupyterhub==5.4.3
  - jupyterlab==4.5.2
  - jupyter-archive==3.4.0
  - jupyter_server==2.17.0
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.5.0
  - python==3.11.*
  - pip==25.1.1
  - regex==2025.11.3
  - sqlite==3.51.1

  # Git, GitHub
  - gh=2.76
  - nbdime=4.0
  
  # Jupyter
  - jupyterlab_widgets=3.0
  - ipywidgets=8.1
  - jupyterlab-latex=4.4

  # MATH 108 and STAT C1000 Packages
  - datascience=0.18
  - numpy=2.3
  - matplotlib=3.10
  - geopandas=1.1
  - openpyxl=3.1
  - pandas=2.3
  - plotly=6.2
  - scikit-learn=1.7
  - scipy=1.16
  - seaborn=0.13
  - statsmodels=0.14
  - sympy=.14
  - folium=0.20
  - nltk=3.9
  - ipympl=0.9
  - requests=2.32
  - httpx=0.28
  - beautifulsoup4=4.13
  - html5lib=1.1
  - polars=1.34

  # pip installed packages, conda is preferred
  - pip:
    - jupyter-shiny-proxy==1.3
    - jupysql==0.10.15
    - pip-tree==4.0.0
    - pipdeptree==2.28.0
    - nbconvert[webpdf]=7.16
    - otter-grader=6.1
    - jupyterlab-myst=2.4
    - jupyterlab-a11y-checker=0.2
